callable: ETL.generate_features.main
kwargs:
  candidates_df: /home/huvi/recom/data/candidates_df.pkl
  external_data:
    cart_num: /home/huvi/recom/data/num_of_to_cart.pkl
    view_num: /home/huvi/recom/data/num_of_view.pkl
    categories: /home/huvi/recom/data/categories.pkl
    sparse_similarities_view: /home/huvi/recom/sparse_data/similarities_view.npz
    sparse_similarities_to_cart: /home/huvi/recom/sparse_data/similarities_to_cart.npz
    PAB_view: /home/huvi/recom/sparse_data/PAB_view.npz
    PAB_cart: /home/huvi/recom/sparse_data/PAB_to_cart.npz
    PB_view: /home/huvi/recom/sparse_data/PB_view.npy
    PB_cart: /home/huvi/recom/sparse_data/PB_to_cart.npy

  output_data:
    exploded_df: /home/huvi/recom/data/exploded_df.pkl
    features_df: /home/huvi/recom/data/features_df.pkl
