callable: ETL.get_categories.main
kwargs:
  data:
    session_items_categories: /home/huvi/recom/data/sess_item_categories.csv
    mapping: /home/huvi/recom/data/reverse_mapping.pkl
    output: /home/huvi/recom/data/categories.pkl
