callable: w2vec.train.main
kwargs:
  n_epochs: 50
  min_count: 5
  model_dir: /home/huvi/recom/data/w2vec/weights
  data:
    cart: /home/huvi/recom/data/w2vec/to_cart_df.pkl
    views: /home/huvi/recom/data/w2vec/view_df.pkl
