callable: L2R.train_catboost.main
kwargs:
  input_data: /home/almokhov/recom/data/features_df.pkl
  device: '0'
  catboost_params:
    iterations: 1000
    verbose: true
    task_type: GPU
    learning_rate: 0.5
  model_fit_params:
    loss: YetiRankPairwise
    train_dir: /home/almokhov/recom/cb_logs/
    add_params:
      custom_metric: 
        - "MAP:top=10"
        - "NDCG:hints=skip_train~false"
        - "PFound:hints=skip_train~false"
  save_dir: /home/almokhov/recom/catboost_yeti.cbm
